"""add task domain tables

Revision ID: 5efd8dd13e9a
Revises: ee0f7959b15c
Create Date: 2026-09-08 13:48:35.379507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efd8dd13e9a'
down_revision: Union[str, Sequence[str], None] = 'ee0f7959b15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('brand_config_json', sa.JSON(), nullable=False),
    sa.Column('selected_plan_ids_json', sa.JSON(), nullable=False),
    sa.Column('interrupt_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('generation_work_item',
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('shot_id', sa.String(length=64), nullable=False),
    sa.Column('skill', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('work_item_id')
    )
    op.create_index(op.f('ix_generation_work_item_task_id'), 'generation_work_item', ['task_id'], unique=False)
    op.create_table('task_error_log',
    sa.Column('error_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('error_id')
    )
    op.create_index(op.f('ix_task_error_log_task_id'), 'task_error_log', ['task_id'], unique=False)
    op.create_table('task_event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_task_event_task_id'), 'task_event', ['task_id'], unique=False)
    op.create_table('generation_attempt',
    sa.Column('attempt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_index', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('returncode', sa.Integer(), nullable=True),
    sa.Column('manifest_json', sa.JSON(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['generation_work_item.work_item_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_generation_attempt_work_item_id'), 'generation_attempt', ['work_item_id'], unique=False)
    op.create_table('sku_output_image',
    sa.Column('image_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.String(length=512), nullable=False),
    sa.Column('shot_id', sa.String(length=64), nullable=False),
    sa.Column('human_decision', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['generation_work_item.work_item_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_sku_output_image_task_id'), 'sku_output_image', ['task_id'], unique=False)
    op.create_table('qa_result',
    sa.Column('qa_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('issues_json', sa.JSON(), nullable=False),
    sa.Column('correction_suggestion', sa.Text(), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['generation_attempt.attempt_id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['generation_work_item.work_item_id'], ),
    sa.PrimaryKeyConstraint('qa_id')
    )
    op.create_index(op.f('ix_qa_result_work_item_id'), 'qa_result', ['work_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_result_work_item_id'), table_name='qa_result')
    op.drop_table('qa_result')
    op.drop_index(op.f('ix_sku_output_image_task_id'), table_name='sku_output_image')
    op.drop_table('sku_output_image')
    op.drop_index(op.f('ix_generation_attempt_work_item_id'), table_name='generation_attempt')
    op.drop_table('generation_attempt')
    op.drop_index(op.f('ix_task_event_task_id'), table_name='task_event')
    op.drop_table('task_event')
    op.drop_index(op.f('ix_task_error_log_task_id'), table_name='task_error_log')
    op.drop_table('task_error_log')
    op.drop_index(op.f('ix_generation_work_item_task_id'), table_name='generation_work_item')
    op.drop_table('generation_work_item')
    op.drop_table('task')
    # ### end Alembic commands ###
