"""init asset library tables

Revision ID: ee0f7959b15c
Revises: 
Create Date: 2026-09-07 12:14:43.342635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee0f7959b15c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_asset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('scene_type', sa.String(length=32), nullable=True),
    sa.Column('light', sa.String(length=32), nullable=True),
    sa.Column('tone', sa.String(length=32), nullable=True),
    sa.Column('style', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_no')
    )
    op.create_index('ix_background_asset_filter', 'background_asset', ['scene_type', 'light', 'tone'], unique=False)
    op.create_index('ix_background_asset_owner', 'background_asset', ['owner_id'], unique=False)
    op.create_index('ix_background_asset_scope_status', 'background_asset', ['scope', 'status', 'deleted'], unique=False)
    op.create_table('model_asset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('age_stage', sa.String(length=16), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=16), nullable=True),
    sa.Column('skin_tone', sa.String(length=16), nullable=True),
    sa.Column('ethnicity_group', sa.String(length=32), nullable=True),
    sa.Column('ethnicity_detail', sa.String(length=32), nullable=True),
    sa.Column('face_shape', sa.String(length=16), nullable=True),
    sa.Column('hair_style', sa.String(length=16), nullable=True),
    sa.Column('style_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_no')
    )
    op.create_index('ix_model_asset_filter', 'model_asset', ['gender', 'age_stage', 'skin_tone', 'ethnicity_group'], unique=False)
    op.create_index('ix_model_asset_owner', 'model_asset', ['owner_id'], unique=False)
    op.create_index('ix_model_asset_scope_status', 'model_asset', ['scope', 'status', 'deleted'], unique=False)
    op.create_table('outfit_asset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('material', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('occasion', sa.String(length=32), nullable=True),
    sa.Column('style', sa.String(length=32), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_no')
    )
    op.create_index('ix_outfit_asset_filter', 'outfit_asset', ['material', 'color', 'occasion'], unique=False)
    op.create_index('ix_outfit_asset_owner', 'outfit_asset', ['owner_id'], unique=False)
    op.create_index('ix_outfit_asset_scope_status', 'outfit_asset', ['scope', 'status', 'deleted'], unique=False)
    op.create_table('background_asset_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('group_key', sa.String(length=32), nullable=False),
    sa.Column('tag_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['background_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'group_key', 'tag_name', name='uk_background_asset_tag')
    )
    op.create_index('ix_background_asset_tag_asset', 'background_asset_tag', ['asset_id'], unique=False)
    op.create_index('ix_background_asset_tag_filter', 'background_asset_tag', ['group_key', 'tag_name'], unique=False)
    op.create_table('model_asset_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('group_key', sa.String(length=32), nullable=False),
    sa.Column('tag_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['model_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'group_key', 'tag_name', name='uk_model_asset_tag')
    )
    op.create_index('ix_model_asset_tag_asset', 'model_asset_tag', ['asset_id'], unique=False)
    op.create_index('ix_model_asset_tag_filter', 'model_asset_tag', ['group_key', 'tag_name'], unique=False)
    op.create_table('outfit_asset_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('group_key', sa.String(length=32), nullable=False),
    sa.Column('tag_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['outfit_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'group_key', 'tag_name', name='uk_outfit_asset_tag')
    )
    op.create_index('ix_outfit_asset_tag_asset', 'outfit_asset_tag', ['asset_id'], unique=False)
    op.create_index('ix_outfit_asset_tag_filter', 'outfit_asset_tag', ['group_key', 'tag_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outfit_asset_tag_filter', table_name='outfit_asset_tag')
    op.drop_index('ix_outfit_asset_tag_asset', table_name='outfit_asset_tag')
    op.drop_table('outfit_asset_tag')
    op.drop_index('ix_model_asset_tag_filter', table_name='model_asset_tag')
    op.drop_index('ix_model_asset_tag_asset', table_name='model_asset_tag')
    op.drop_table('model_asset_tag')
    op.drop_index('ix_background_asset_tag_filter', table_name='background_asset_tag')
    op.drop_index('ix_background_asset_tag_asset', table_name='background_asset_tag')
    op.drop_table('background_asset_tag')
    op.drop_index('ix_outfit_asset_scope_status', table_name='outfit_asset')
    op.drop_index('ix_outfit_asset_owner', table_name='outfit_asset')
    op.drop_index('ix_outfit_asset_filter', table_name='outfit_asset')
    op.drop_table('outfit_asset')
    op.drop_index('ix_model_asset_scope_status', table_name='model_asset')
    op.drop_index('ix_model_asset_owner', table_name='model_asset')
    op.drop_index('ix_model_asset_filter', table_name='model_asset')
    op.drop_table('model_asset')
    op.drop_index('ix_background_asset_scope_status', table_name='background_asset')
    op.drop_index('ix_background_asset_owner', table_name='background_asset')
    op.drop_index('ix_background_asset_filter', table_name='background_asset')
    op.drop_table('background_asset')
    # ### end Alembic commands ###
